project:
  type: book

book:
  title: "Mapeo de ErosiÃ³n del Suelo a Nivel Nacional: Un Manual con la MetodologÃ­a RUSLE y el Paquete rgee<br>ğŸ“šğŸï¸ğŸŒ±ğŸŒ§ï¸ğŸšœğŸ”ğŸ“‰ğŸ’¨ğŸŒ¾ğŸ—ºï¸<br>"
  author: "Antony Barja <br> Tesista de LABSAF"
  date: "last-modified"
  repo-url: https://github.com/edzer/sdsr/
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - intro.qmd
    - study_area.qmd
    - methodology.qmd
    - results.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
     light: flatly
     dark: theme-dark.scss
  pdf:
    documentclass: scrreprt