project:
  type: book

lang: es
language: 
  title-block-author-single: "AUTOR"
  title-block-published: "PUBLICADO"  

date: 08/02/2023
date-modified: last-modified


book:
  title: "Mapeo de ErosiÃ³n del Suelo a Nivel Nacional empleando la MetodologÃ­a de RUSLE y rgee<br>ğŸ“šğŸï¸ğŸŒ±ğŸŒ§ï¸ğŸšœğŸ”ğŸ“‰ğŸ’¨ğŸŒ¾ğŸ—ºï¸<br>"
  author: "<i class='bi bi-person-fill'></i> Antony Barja<div class='quarto-title-meta-heading'><div><i class='bi bi-person-check-fill'></i> Revizado por: Ing.Carlos Carbajal</div></div><div><i class='bi bi-buildings-fill'></i> AfiliaciÃ³n: INIA-LABSAF</div>"
  repo-url: https://ambarja.github.io/inia-workshop-rusle-with-rgee/
  sharing: [twitter, facebook,linkedin]

  chapters:
    - index.qmd
    - 01_requeriments.qmd
    - 02_rgee-setup.qmd
    - 03_methodology.qmd
    - 04_rusle_with_rgee.qmd
    - 05_results.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
     light: geoscss/theme-light.scss
     dark: geoscss/theme-dark.scss
    mermaid: 
      theme: forest
    html-math-method: katex

  pdf:
    documentclass: scrreprt